version: 2
run:
  allow-parallel-runners: true
  timeout: 5m
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - gocritic
issues:
  exclude-rules:
    - linters:
        - dupl
      path: _test\.go
