run:
  allow-parallel-runners: true
  timeout: 5m
linters:
  default: none
  enable:
    - dogsled
    - dupl
    - errorlint
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - predeclared
    - revive
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
issues:
  exclude-rules:
    - linters:
        - dupl
        - lll
      path: _test\.go
