---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - history.yu-kod.github.io
  resources:
  - kronoforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - history.yu-kod.github.io
  resources:
  - kronoforms/finalizers
  verbs:
  - update
- apiGroups:
  - history.yu-kod.github.io
  resources:
  - kronoforms/status
  verbs:
  - get
  - patch
  - update
