apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronoform-demo-app
  namespace: default
  labels:
    app: kronoform-demo
    app.kubernetes.io/name: kronoform-demo
    app.kubernetes.io/managed-by: kronoform
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kronoform-demo
  template:
    metadata:
      labels:
        app: kronoform-demo
    spec:
      containers:
        - name: demo-app
          image: nginx:1.24
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: "v1.0"
            - name: MESSAGE
              value: "Deployed with Kronoform history tracking"
---
apiVersion: v1
kind: Service
metadata:
  name: kronoform-demo-service
  namespace: default
  labels:
    app: kronoform-demo
    app.kubernetes.io/name: kronoform-demo
    app.kubernetes.io/managed-by: kronoform
spec:
  selector:
    app: kronoform-demo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
