name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: make generate

      - name: Generate manifests
        run: make manifests

      - name: Run tests
        run: make test

      - name: Build manager
        run: make build

      - name: Build kubectl plugin
        run: make build-plugin

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
