name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Generate code and manifests
        run: |
          make generate
          make manifests

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -o bin/kubectl-kronoform-linux-amd64 cmd/kubectl-kronoform/main.go
          GOOS=linux GOARCH=arm64 go build -o bin/kubectl-kronoform-linux-arm64 cmd/kubectl-kronoform/main.go
          GOOS=darwin GOARCH=amd64 go build -o bin/kubectl-kronoform-darwin-amd64 cmd/kubectl-kronoform/main.go
          GOOS=darwin GOARCH=arm64 go build -o bin/kubectl-kronoform-darwin-arm64 cmd/kubectl-kronoform/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/kubectl-kronoform-windows-amd64.exe cmd/kubectl-kronoform/main.go

          # Build manager
          make build

      - name: Create release bundle
        run: |
          # Create install bundle
          make build-installer IMG=ghcr.io/yu-kod/kronoform:${GITHUB_REF#refs/tags/}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/kubectl-kronoform-*
            dist/install.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
